Install the latest GnuPG in Docker images for enhanced security

diff --git a/backend/Dockerfile-production b/backend/Dockerfile-production
--- a/backend/Dockerfile-production
+++ b/backend/Dockerfile-production
@@ -17,13 +17,17 @@
 # https://mcr.microsoft.com/artifact/mar/dotnet/sdk/tags
 FROM mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim-amd64 AS build
 
-RUN \
-  apt-get update && \
-  apt-get upgrade --assume-yes && \
-  rm \
-    --recursive \
-    --force \
-    /var/lib/apt/lists/*
+# RUN \
+#   apt-get update && \
+#   apt-get upgrade --assume-yes && \
+#   apt-get install \
+#     --assume-yes \
+#     --no-install-recommends \
+#     gnupg2 && \
+#   rm \
+#     --recursive \
+#     --force \
+#     /var/lib/apt/lists/*
 
 COPY ./ /app
 
@@ -57,8 +61,52 @@ RUN \
   apt-get install \
     --assume-yes \
     --no-install-recommends \
+    curl && \
+  rm \
+    --recursive \
+    --force \
+    /var/lib/apt/lists/*
+
+# Install up-to-date GnuPG from the official GnuPG repository.
+# For available versions see https://repos.gnupg.org/deb/gnupg/
+# The fingerprint was taken from https://repos.gnupg.org/deb/gnupg/bookworm/
+# Keep the version in sync with the one in the other Dockerfiles of this
+# repository and with the one of the `machine` repository specified in the
+# `local.yml` Ansible script.
+ENV GNUPG_VERSION=2.4.8-2
+ENV GNUPG_FINGERPRINT=32097B719B3745D6E61DDA1B85C45AE3E1A2B355
+RUN set -eux && \
+  version_codename=$(env --ignore-environment bash -c '. /etc/os-release; echo $VERSION_CODENAME') && \
+  apt-get update && \
+  apt-get install \
+    --assume-yes \
+    --no-install-recommends \
     curl \
-    gnupg && \
+    gnupg2 && \
+  curl \
+    --silent \
+    --show-error \
+    https://repos.gnupg.org/deb/gnupg/${version_codename}/gnupg-signing-key.gpg \
+    | gpg --dearmor \
+    > /usr/share/keyrings/gnupg-keyring.gpg && \
+  fingerprint=$(gpg \
+    --batch \
+    --with-colons \
+    --import-options show-only \
+    --import /usr/share/keyrings/gnupg-keyring.gpg \
+    | awk -F':' '$1=="fpr"{print $10}') && \
+  if [ "${fingerprint}" != "${GNUPG_FINGERPRINT}" ]; then \
+      echo "Error: Key fingerprint mismatch, got ${fingerprint} and expected ${GNUPG_FINGERPRINT}"; \
+      exit 1; \
+  fi && \
+  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gnupg-keyring.gpg] https://repos.gnupg.org/deb/gnupg/${version_codename}/ ${version_codename} main" \
+    > /etc/apt/sources.list.d/gnupg.list && \
+  apt-get update && \
+  apt-get install \
+    --assume-yes \
+    --no-install-recommends \
+    dirmngr \
+    gnupg2=${GNUPG_VERSION} && \
   rm \
     --recursive \
     --force \
@@ -70,6 +118,14 @@ COPY \
   --from=build \
   /app/src/bin/Release/net9.0/publish \
   ./
+
+RUN \
+  mkdir --parents \
+    /root/.gnupg && \
+  chmod u=rwx,g=,o= \
+    /root/.gnupg && \
+  echo "allow-loopback-pinentry" \
+    > /root/.gnupg/gpg-agent.conf
 
 RUN \
   ln --symbolic ./Metabase.dll ./App.dll
