Include props file with common csproj settings in the Dockerfile

diff --git a/backend/Dockerfile.development b/backend/Dockerfile.development
--- a/backend/Dockerfile.development
+++ b/backend/Dockerfile.development
@@ -21,34 +21,34 @@ RUN \
 RUN \
   apt-get update && \
   apt-get install \
-    --assume-yes \
-    --no-install-recommends \
-    adduser && \
+  --assume-yes \
+  --no-install-recommends \
+  adduser && \
   existing_user_name="$( (getent passwd ${USER_ID} 2>/dev/null || true) | cut --delimiter=: --fields=1)" && \
   if test -n "${existing_user_name}"; then \
-    deluser "${existing_user_name}"; \
+  deluser "${existing_user_name}"; \
   fi && \
   existing_group_name="$( (getent group ${GROUP_ID} 2>/dev/null || true) | cut --delimiter=: --fields=1)" && \
   if test -n "${existing_group_name}"; then \
-    delgroup "${existing_group_name}"; \
+  delgroup "${existing_group_name}"; \
   fi && \
   addgroup \
-    --system \
-    --gid ${GROUP_ID} \
-    us && \
+  --system \
+  --gid ${GROUP_ID} \
+  us && \
   adduser \
-    --system \
-    --home /home/me \
-    --uid ${USER_ID} \
-    --ingroup us \
-    me && \
+  --system \
+  --home /home/me \
+  --uid ${USER_ID} \
+  --ingroup us \
+  me && \
   apt-get remove \
-    --assume-yes \
-    adduser && \
+  --assume-yes \
+  adduser && \
   rm \
-    --recursive \
-    --force \
-    /var/lib/apt/lists/*
+  --recursive \
+  --force \
+  /var/lib/apt/lists/*
 
 #############
 # As `root` #
@@ -74,34 +74,34 @@ RUN \
 # https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
 RUN apt-get update \
   && apt-get install \
-    --assume-yes \
-    --no-install-recommends \
-    curl \
-    editorconfig \
-    gawk \
-    gnupg2 \
-    lldb \
-    make \
-    procps \
-    tini \
+  --assume-yes \
+  --no-install-recommends \
+  curl \
+  editorconfig \
+  gawk \
+  gnupg2 \
+  lldb \
+  make \
+  procps \
+  tini \
   && rm \
-    --recursive \
-    --force \
-    /var/lib/apt/lists/*
+  --recursive \
+  --force \
+  /var/lib/apt/lists/*
 
 # Add dependencies for interactive examples in ./examples
 # `jq` can be used to format and filter JSON data
 RUN apt-get update \
   && apt-get install \
-    --assume-yes \
-    --no-install-recommends \
-    bash \
-    jq \
-    neovim \
+  --assume-yes \
+  --no-install-recommends \
+  bash \
+  jq \
+  neovim \
   && rm \
-    --recursive \
-    --force \
-    /var/lib/apt/lists/*
+  --recursive \
+  --force \
+  /var/lib/apt/lists/*
 
 # Install up-to-date GnuPG from the official GnuPG repository.
 # For the signing-key fingerprint see https://repos.gnupg.org/deb/gnupg/noble/
@@ -111,47 +111,47 @@ RUN \
   version_codename="$(env --ignore-environment bash -c '. /etc/os-release; echo $VERSION_CODENAME')" && \
   apt-get update && \
   apt-get install \
-    --assume-yes \
-    --no-install-recommends \
-    curl \
-    gnupg2 && \
+  --assume-yes \
+  --no-install-recommends \
   curl \
-    --silent \
-    --show-error \
-    "https://repos.gnupg.org/deb/gnupg/${version_codename}/gnupg-signing-key.gpg" \
-    | gpg --dearmor \
-    > /usr/share/keyrings/gnupg-keyring.gpg && \
+  gnupg2 && \
+  curl \
+  --silent \
+  --show-error \
+  "https://repos.gnupg.org/deb/gnupg/${version_codename}/gnupg-signing-key.gpg" \
+  | gpg --dearmor \
+  > /usr/share/keyrings/gnupg-keyring.gpg && \
   fingerprint=$(gpg \
-    --batch \
-    --with-colons \
-    --import-options show-only \
-    --import /usr/share/keyrings/gnupg-keyring.gpg \
-    | awk -F':' '$1=="fpr"{print $10}') && \
+  --batch \
+  --with-colons \
+  --import-options show-only \
+  --import /usr/share/keyrings/gnupg-keyring.gpg \
+  | awk -F':' '$1=="fpr"{print $10}') && \
   if [ "${fingerprint}" != "${GNUPG_FINGERPRINT}" ]; then \
-      echo "Error: Key fingerprint mismatch, got ${fingerprint} and expected ${GNUPG_FINGERPRINT}"; \
-      exit 1; \
+  echo "Error: Key fingerprint mismatch, got ${fingerprint} and expected ${GNUPG_FINGERPRINT}"; \
+  exit 1; \
   fi && \
   echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gnupg-keyring.gpg] https://repos.gnupg.org/deb/gnupg/${version_codename}/ ${version_codename} main" \
-    > /etc/apt/sources.list.d/gnupg.list && \
+  > /etc/apt/sources.list.d/gnupg.list && \
   apt-get update && \
   apt-get install \
-    --assume-yes \
-    --no-install-recommends \
-    dirmngr \
-    gnupg2 && \
+  --assume-yes \
+  --no-install-recommends \
+  dirmngr \
+  gnupg2 && \
   rm \
-    --recursive \
-    --force \
-    /var/lib/apt/lists/*
+  --recursive \
+  --force \
+  /var/lib/apt/lists/*
 
 ENV HOME=/home/me
 RUN mkdir --parents ${HOME}/app \
   && chown \
-    me:us \
-    ${HOME} \
+  me:us \
+  ${HOME} \
   && chown \
-    me:us \
-    ${HOME}/app \
+  me:us \
+  ${HOME}/app \
   && ln --symbolic ${HOME}/app /app
 
 ###########
@@ -176,10 +176,11 @@ RUN dotnet tool restore \
 
 RUN mkdir ./src \
   && mkdir ./test
-COPY --chown=me:us ./src/Metabase.csproj ./src/
-COPY --chown=me:us ./test/Metabase.Tests.csproj ./test/
+COPY --chown=me:us ./src/*.csproj ./src/
+COPY --chown=me:us ./test/*.Tests.csproj ./test/
 
-COPY --chown=me:us ./Metabase.sln ./
+COPY --chown=me:us ./Directory.Build.props ./
+COPY --chown=me:us ./*.sln ./
 RUN dotnet clean \
   && dotnet restore \
   && dotnet tool run dotnet-sos install # https://github.com/dotnet/diagnostics/blob/master/documentation/installing-sos-instructions.md
@@ -212,23 +213,23 @@ EOT
 RUN mkdir --parents \
   ./src/logs \
   && mkdir --parents \
-    ./src/bin \
-    ./src/obj \
+  ./src/bin \
+  ./src/obj \
   && mkdir --parents \
-    ./test/bin \
-    ./test/obj \
+  ./test/bin \
+  ./test/obj \
   && mkdir --parents \
-    ${HOME}/.nuget \
-    ${HOME}/.dotnet \
+  ${HOME}/.nuget \
+  ${HOME}/.dotnet \
   && mkdir --parents \
-    ${HOME}/.vscode-server \
-    ${HOME}/.vscode-server-insiders \
+  ${HOME}/.vscode-server \
+  ${HOME}/.vscode-server-insiders \
   && mkdir --parents \
-    ${HOME}/.dotnet/corefx/cryptography/x509stores \
+  ${HOME}/.dotnet/corefx/cryptography/x509stores \
   && mkdir --parents \
-    ${HOME}/.gnupg \
+  ${HOME}/.gnupg \
   && chmod u=rwx,g=,o= \
-    ${HOME}/.gnupg
+  ${HOME}/.gnupg
 
 ENV SHELL=/bin/bash
 
